import fs from 'node:fs'
import path from 'node:path'
import consola from 'consola'
import { getRepoRoot } from './config'

/** .env.local 中的键值对 */
export type SecretsMap = Map<string, string>

/**
 * Token 匹配规则
 * 匹配 export KEY="value" 或 KEY="value" 形式中含敏感关键词的行
 */
const SECRET_KEY_PATTERNS = [
  /API_KEY/i,
  /TOKEN/i,
  /SECRET/i,
  /PASSWORD/i,
  /PRIVATE_KEY/i,
  /CREDENTIAL/i,
]

/**
 * 值看起来像真实 token 的模式（排除占位符和空值）
 */
const TOKEN_VALUE_PATTERN = /^[\w\-/.+:@]{8,}$/

/** 占位符格式：{{DOTFILES_SECRET:KEY_NAME}} */
function makePlaceholder(key: string): string {
  return `{{DOTFILES_SECRET:${key}}}`
}

const PLACEHOLDER_RE = /\{\{DOTFILES_SECRET:([^}]+)\}\}/g

/**
 * 检测一行是否包含敏感 token
 * 返回 { key, value } 或 null
 */
function detectSecret(line: string): { key: string, value: string, full: string } | null {
  // 匹配 export KEY="value" / export KEY='value' / KEY=value
  const m = line.match(/^(\s*export\s+)?([A-Z_][A-Z0-9_]*)=["']?([^"'\s#]*)["']?/)
  if (!m)
    return null

  const key = m[2]
  const value = m[3]

  // 检查 key 是否匹配敏感关键词
  const isSensitiveKey = SECRET_KEY_PATTERNS.some(p => p.test(key))
  if (!isSensitiveKey)
    return null

  // 排除空值和已经是占位符的值
  if (!value || value.startsWith('{{DOTFILES_SECRET:'))
    return null

  // 值看起来像真实 token
  if (TOKEN_VALUE_PATTERN.test(value)) {
    return { key, value, full: line }
  }

  return null
}

/**
 * 扫描文件内容，检测所有敏感 token
 */
export function detectSecrets(content: string): { key: string, value: string }[] {
  const secrets: { key: string, value: string }[] = []
  const lines = content.split('\n')

  for (const line of lines) {
    const secret = detectSecret(line)
    if (secret)
      secrets.push({ key: secret.key, value: secret.value })
  }

  return secrets
}

/**
 * 将文件内容中的真实 token 替换为占位符
 */
export function maskSecrets(content: string, secrets: { key: string, value: string }[]): string {
  let masked = content
  for (const { key, value } of secrets) {
    // 只替换 KEY=value 形式中的 value 部分
    const escaped = value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
    const re = new RegExp(`(${key}=["']?)${escaped}(["']?)`, 'g')
    masked = masked.replace(re, `$1${makePlaceholder(key)}$2`)
  }
  return masked
}

/**
 * 将文件内容中的占位符恢复为真实 token
 */
export function unmaskSecrets(content: string, secretsMap: SecretsMap): { content: string, missing: string[] } {
  const missing: string[] = []
  const unmasked = content.replace(PLACEHOLDER_RE, (match, key: string) => {
    const value = secretsMap.get(key)
    if (value !== undefined)
      return value
    missing.push(key)
    return match
  })
  return { content: unmasked, missing }
}

/**
 * 检测内容中存在的占位符
 */
export function findPlaceholders(content: string): string[] {
  const keys: string[] = []
  let m: RegExpExecArray | null
  // eslint-disable-next-line no-cond-assign
  while ((m = PLACEHOLDER_RE.exec(content)) !== null) {
    keys.push(m[1])
  }
  return keys
}

// --- .env.local 管理 ---

function getEnvLocalPath(): string {
  return path.resolve(getRepoRoot(), '.env.local')
}

/**
 * 读取 .env.local 文件
 */
export function loadSecretsFile(): SecretsMap {
  const envPath = getEnvLocalPath()
  const map: SecretsMap = new Map()

  if (!fs.existsSync(envPath))
    return map

  const content = fs.readFileSync(envPath, 'utf-8')
  for (const line of content.split('\n')) {
    const trimmed = line.trim()
    if (!trimmed || trimmed.startsWith('#'))
      continue
    const eqIdx = trimmed.indexOf('=')
    if (eqIdx === -1)
      continue
    const key = trimmed.slice(0, eqIdx).trim()
    let value = trimmed.slice(eqIdx + 1).trim()
    // 去掉首尾引号
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith('\'') && value.endsWith('\'')))
      value = value.slice(1, -1)
    map.set(key, value)
  }

  return map
}

/**
 * 将新发现的 secrets 合并写入 .env.local
 */
export function saveSecrets(newSecrets: { key: string, value: string }[]): void {
  const envPath = getEnvLocalPath()
  const existing = loadSecretsFile()

  let changed = false
  for (const { key, value } of newSecrets) {
    if (!existing.has(key) || existing.get(key) !== value) {
      existing.set(key, value)
      changed = true
    }
  }

  if (!changed)
    return

  const lines = [
    '# Auto-generated by @yunyoujun/dotfiles',
    '# This file stores real token values locally. DO NOT commit this file.',
    '',
  ]

  for (const [key, value] of existing) {
    lines.push(`${key}="${value}"`)
  }

  lines.push('')
  fs.writeFileSync(envPath, lines.join('\n'), 'utf-8')
  consola.info(`Secrets saved to ${envPath}`)

  // 确保 .gitignore 包含 .env.local
  ensureGitignore()
}

function ensureGitignore(): void {
  const gitignorePath = path.resolve(getRepoRoot(), '.gitignore')
  if (!fs.existsSync(gitignorePath))
    return

  const content = fs.readFileSync(gitignorePath, 'utf-8')
  if (!content.includes('.env.local')) {
    fs.appendFileSync(gitignorePath, '\n.env.local\n')
    consola.info('Added .env.local to .gitignore')
  }
}
